# Generated by Django 2.0.13 on 2019-07-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='adrss1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='adrss2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
