# Generated by Django 2.0.13 on 2019-07-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190703_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(max_length=70, null=True),
        ),
    ]
