# Generated by Django 2.0.13 on 2019-07-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phno',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
