# Generated by Django 2.2 on 2019-07-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_phno'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
    ]
